<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    
     public function listerArmesFamiliales()
    {
        $qb=$this->_em->createQueryBuilder();
//        $qb = new \Doctrine\ORM\QueryBuilder();
        $qb->select("c");
        $qb->from("AppBundle:Produit","c");
        $qb->orderBy("c.prix", "ASC");
        
        
        $res = $qb->getQuery();
         
        $produits = $res->setMaxResults(5)->getResult();
        
        // Envoie la var 'mesProduits' 
        return $produits;
    }
    
    
    public function listerArmesPrestiges()
    {
        $qb=$this->_em->createQueryBuilder();
//        $qb = new \Doctrine\ORM\QueryBuilder();
        $qb->select("c");
        $qb->from("AppBundle:Produit","c");
        $qb->orderBy("c.prix", "DESC");
        
        
        $res = $qb->getQuery();
         
        $produits = $res->setMaxResults(5)->getResult();
         return $produits;
    }
    
    public function triProduits()
    {
        $qb=$this->_em->createQueryBuilder();
//        $qb = new \Doctrine\ORM\QueryBuilder();
        $qb->select("c");
        $qb->from("AppBundle:Produit","c");
        $qb->orderBy("c.prix", "ASC");
        
        
        $res = $qb->getQuery();
         
        $produits = $res->getResult();
        
        // Envoie la var 'mesProduits' 
        return $produits;
    }
}
