# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    
    encoders:
        Symfony\Component\Security\Core\User\User : plaintext
        AppBundle\Entity\Client: plaintext
    
    role_hierarchy:
        ROLE_ADMIN: ROLE_MODO
        ROLE_MODO: ROLE_SIMPLE

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_database:
            entity:
                class: AppBundle:Client
                property: login
        in_memory:
            memory: 
                users:
                    warsa:
                        password: warsa
                        roles: 'ROLE_SIMPLE'
                    helene:
                        password: helene
                        roles: 'ROLE_MODO'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
    
    access_control:
        - { path: admin/*, roles: ROLE_ADMIN }
        - { path: admin/client*, roles: ROLE_MODO }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            
            provider: in_database

            http_basic: ~
            
            #provider: in_memory
            #http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: /login
                check_path: login
            logout:
                path: logout
                target: /
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
