# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    client_service:
        class: AppBundle\Service\ClientService
        arguments: ["@doctrine.orm.entity_manager", "@email_service", "@logger"]  
        # permet de passer un argument au constructeur de ClientService
        
    email_service:
        class: AppBundle\Service\MailServiceBidon
        arguments: ["@mailer"]
        

        
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

